- type: replace
  path: /releases/name=os-conf?
  value:
    name: os-conf
    version: latest

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: user_add
    release: os-conf
    properties:
      users:
      - name: vcap
        crypted_password: '$6$someSalt$TPoxmAaKskFliMR/QluOjXRCrZ59gL/6VVxRfFaoCXnALX0IjXsPwjyrvp8ra/fChXWclcrlhR5e/h7ic4Vfd.'

- type: replace
  path: /instance_groups/name=haproxy/jobs/-
  value:
    name: user_add
    release: os-conf
    properties:
      users:
      - name: vcap
        crypted_password: '$6$someSalt$TPoxmAaKskFliMR/QluOjXRCrZ59gL/6VVxRfFaoCXnALX0IjXsPwjyrvp8ra/fChXWclcrlhR5e/h7ic4Vfd.'
