---
deployment-name: cf-rabbitmq

stemcell-version: 3421.24

haproxy-instances: 1

rabbitmq-management-username: admin
rabbitmq-management-password: admin
rabbitmq-management-hostname: rabbitmq

rabbitmq-broker-username: broker
rabbitmq-broker-password: broker

use-native-clustering-formation: false

cluster-partition-handling-strategy: autoheal

syslog-host:
syslog-port:

cf-admin-password: admin
cf-admin-username: admin

bosh-domain: bosh-lite.com
