---
deployment-name: cf-rabbitmq
cf-rabbitmq-release-name: cf-rabbitmq

# Some of our current tests (based on Prof) do not work with stemcell versions
# starting from 3363.12 because they randomise vcap passwords and our tests use
# the default ones
stemcell-version: 3262.2

haproxy-instances: 2
rabbitmq-management-username: admin
rabbitmq-management-password: admin
rabbitmq-broker-username: broker
rabbitmq-broker-password: broker
haproxy-stats-username: haproxy
haproxy-stats-password: haproxy
syslog-host:
syslog-port:
