---
util-linux/util-linux_2.20.1.orig.tar.gz:
  object_id: 00358c94-0d4b-4db5-bb8f-f8b6df178818
  sha: d1dcff8d39e1a821cb0efda31a38452d12fd6b52
  size: 6174190
cf-cli/cf-linux-amd64-6.19.0.tgz:
  object_id: cda6b19b-8df2-4583-a1b5-a0ab78ba191d
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
rabbitmq-server/rabbitmq_clusterer-3.5.7.ez:
  object_id: 6a564af0-06cd-4b4a-bf2f-17ecb6215cfe
  sha: 2df9cd942c8edbd00b10530b8af63c73d49ad153
  size: 57497
erlang/otp_src_oss_18.1.tgz:
  object_id: 6cf4831f-727d-44b5-9cd2-1bb33c25b4c5
  sha: cf5a7e63074a4743e976d87b5f9fe80deac61cfe
  size: 68197399
golang/go1.6.3.linux-amd64.tar.gz:
  object_id: 7d05939b-fe46-4ee4-a4d3-9e81386dae27
  sha: 5e916ba4dd8c2fc43beafca4c08b334c4d0686f3
  size: 84856920
java/jre1.8.0_102.tar.gz:
  object_id: 47eaf4d5-39ff-410d-8f27-cebf479a7113
  sha: 826e439a697b4506455e8fbb7aa949e774b18992
  size: 71885713
haproxy/haproxy-1.5.18.tar.gz:
  object_id: f892c0e4-a898-449e-9993-f3aabf5f4541
  sha: 041c02197316ec342aecfe52e989c70b49856063
  size: 1360582
rabbitmq-server/rabbitmq-server-generic-unix-3.5.8.tar.gz:
  object_id: 651b84dc-1ed3-4900-86c2-1b954b742d9e
  sha: 5e89d61291b4bc6865097fa57c92e5214dce239a
  size: 4222924
