---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.2.1.tgz:
  size: 60518443
  object_id: 792f8191-7a75-4088-54e5-83e080471e06
  sha: sha256:2c912c71f361a1e4b0f228de18c6fb120fcc1afa1c6e46ee33acfb5e575337f6
# this comment prevents git conflicts
golang/go1.20.4.linux-amd64.tar.gz:
  size: 100148454
  object_id: ad0266f4-f880-4073-5d28-a092af4e1c53
  sha: sha256:698ef3243972a51ddb4028e4a1ac63dc6d60821bf18e59a807e051fee0a385bd
# this comment prevents git conflicts
haproxy/haproxy-2.6.13.tar.gz:
  size: 4065839
  object_id: 759eebd7-e614-46ec-6af0-0a9ba76f50fc
  sha: sha256:d69ff5233dbca657132ef280d111222ec1e33f5be1c1937d4e9ff516f63f5243
# this comment prevents git conflicts
openssl/openssl-1.1.1u.tar.gz:
  size: 9892176
  object_id: b4fa909c-5f6c-4da5-40e8-7b019685d0c1
  sha: sha256:e2f8d84b523eecd06c7be7626830370300fbcc15386bf5142d72758f6963ebc6
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.24.tar.xz:
  size: 14989728
  object_id: 493a7aa0-6430-41f6-659b-112470520bb5
  sha: sha256:28e09e4f0d192ac6ae6de5ece11f27c8f0c8cb2d2819963ab434f71874491785
