---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.1.tgz:
  size: 59838313
  object_id: d516d415-e382-4bb6-70e0-776cb241c556
  sha: sha256:59fff0a5d9bfac7c8dc3edc58dafdf72121ae89353c33c375c6c4684bedb1d28
# this comment prevents git conflicts
golang/go1.18.linux-amd64.tar.gz:
  size: 141702072
  object_id: eeef597d-b11b-47d1-46b3-1d9f718d0cd1
  sha: sha256:e85278e98f57cdb150fe8409e6e5df5343ecb13cebf03a5d5ff12bd55a80264f
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1n.tar.gz:
  size: 9850712
  object_id: 99991ec8-3764-4c48-6a3d-330be82f48ac
  sha: sha256:40dceb51a4f6a5275bde0e6bf20ef4b91bfc32ed57c0552e2e8e15463372b17a
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.27.tar.xz:
  size: 15713376
  object_id: 1530e7f6-95be-41fc-5c8c-fdfe30517778
  sha: sha256:55569e00710ae54ff2801c1bac18c0360e00ecceee2949744be1a3e2f362f4c8
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.13.tar.xz:
  size: 12660820
  object_id: 66250eee-cc08-4db0-70ac-44dfdfd8b404
  sha: sha256:4672fad92a815b879cc78a5a9fd28445152b61745d68acd50432c15f96792171
