basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_21.3.8.6.tgz:
  size: 55208469
  object_id: e48afa4a-9ad6-47b5-49c7-f5264efac199
  sha: sha256:824c95ec6753fcfc053d5a5dd753a85f2edb421898ffebd435189456b2b602f3
golang/go1.12.7.linux-amd64.tar.gz:
  size: 127959471
  object_id: be80d547-5e2e-4625-408c-0b0d7ecdbf6e
  sha: sha256:66d83bfb5a9ede000e33c6579a91a29e6b101829ad41fffb5c5bb6c900e109d9
golang/go1.12.8.linux-amd64.tar.gz:
  size: 127961104
  sha: sha256:bd26cd4962a362ed3c11835bca32c2e131c2ae050304f2c4df9fa6ded8db85d2
haproxy/haproxy-1.8.20.tar.gz:
  size: 2083917
  object_id: 71408931-a167-4faa-623d-d5759178cf59
  sha: sha256:3228f78d5fe1dfbaccf41bf387e36b08eeef6e16330053cafde5fa303e262b16
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.17.tar.xz:
  size: 9982364
  object_id: 2a86af8f-55e4-4a13-7b9a-33b4ca55c761
  sha: sha256:83abd26dc2f27ea6eee85324163aecd36f1b861e58a027df83f631cbd89ead5d
