---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-21/otp_src_oss_21.3.8.13.tgz:
  size: 55632180
  object_id: 378cba6d-0123-4fcf-6ef9-b4e614be1a0f
  sha: sha256:c3196f6c697997337a96fe7ddeb4b6a3c01345e947f97653587a5f82d24a24fc
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.2.7.tgz:
  size: 57391759
  object_id: 06773d72-ea0d-4805-7ec3-79f2cdd98e8b
  sha: sha256:d64a844460c2566b61f5a3ddd2720ec5b88a652e2f21721381ca31835ba26c90
# this comment prevents git conflicts
golang/go1.13.7.linux-amd64.tar.gz:
  size: 120071076
  object_id: 1fbeff6a-75c6-4e53-5ef7-e9e364ee9389
  sha: sha256:b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3
# this comment prevents git conflicts
haproxy/haproxy-1.8.23.tar.gz:
  size: 2101424
  object_id: 9fd26fcd-ce8d-4a81-75f4-bb0780ada3d6
  sha: sha256:de919164876ee0501e1ef01ca5ccc0d3bda2b96003f9d240f7b856010ccbf7eb
# this comment prevents git conflicts
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.23.tar.xz:
  size: 10031964
  object_id: e9bc0d22-e0b7-4f9a-7f69-63ec8f5a747f
  sha: sha256:b6a658b72aa0f5599b0bb5ec4de22f985e4b88c05669114b6044281430e5dcc8
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.2.tar.xz:
  size: 11642480
  object_id: bdf99c83-5a56-4adf-6f6b-6f7a0c3c9ed2
  sha: sha256:e403744f23d0b336c177a17f843f7172dfb8b93b2866f34756dd0e404848b85b
