---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.3.4.6.tgz:
  size: 57703968
  object_id: 8ad1187e-c94e-4dbe-41e5-67cc3e77f5f3
  sha: sha256:a26b6986ed3e01b2709f2760fcc9806d13b1369c31f80e296a10ac641cdacfa0
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.0.5.tgz:
  size: 59337075
  object_id: fed62eff-4a02-477d-7929-27db487f74e9
  sha: sha256:c5308e442181d282de3729391152ddd962bfb00fe4ca19daca2ccbffe3a11c2b
# this comment prevents git conflicts
golang/go1.17.linux-amd64.tar.gz:
  size: 134787877
  object_id: 0c968a2e-1d83-466f-6c08-3408e53fcabc
  sha: sha256:6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1l.tar.gz:
  size: 9834044
  object_id: 28fcdfb5-65a8-452d-5a89-42a8f44e69eb
  sha: sha256:0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.22.tar.xz:
  size: 15654772
  object_id: ea62f66b-b2fc-4e1a-633d-73e1a3d2be62
  sha: sha256:70873cbfc12615a13b722b32e484da8c964c6561ac022e2faa9c4ed15ff9450a
