---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-21/otp_src_oss_21.3.8.11.tgz:
  size: 55225208
  object_id: 02bb8511-8560-480c-415d-98b101d28bff
  sha: sha256:0effce4bc95b138aa9f1b0f58d3dff080a813715c94d81f37e72036494f38e14
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.2.tgz:
  size: 56986811
  object_id: 4cb12bc2-ce70-4d0d-6d7e-63a71d627861
  sha: sha256:0e049cb564db0afe7adf6f9e5b6a91f182275713cdf84c1c31af0d345186e789
# this comment prevents git conflicts
golang/go1.13.5.linux-amd64.tar.gz:
  size: 120074076
  object_id: d32d15d3-1de5-4dfd-692c-e8267085b3d8
  sha: sha256:512103d7ad296467814a6e3f635631bd35574cab3369a97a323c9a585ccaa569
# this comment prevents git conflicts
haproxy/haproxy-1.8.23.tar.gz:
  size: 2101424
  object_id: 9fd26fcd-ce8d-4a81-75f4-bb0780ada3d6
  sha: sha256:de919164876ee0501e1ef01ca5ccc0d3bda2b96003f9d240f7b856010ccbf7eb
# this comment prevents git conflicts
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.23.tar.xz:
  size: 10031964
  object_id: e9bc0d22-e0b7-4f9a-7f69-63ec8f5a747f
  sha: sha256:b6a658b72aa0f5599b0bb5ec4de22f985e4b88c05669114b6044281430e5dcc8
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.2.tar.xz:
  size: 11642480
  object_id: bdf99c83-5a56-4adf-6f6b-6f7a0c3c9ed2
  sha: sha256:e403744f23d0b336c177a17f843f7172dfb8b93b2866f34756dd0e404848b85b
