---
golang/go1.2.1.linux-amd64.tar.gz:
  object_id: c87bdd9b-8d34-43cc-b84c-bb3c493a1026
  sha: 7605f577ff6ac2d608a3a4e829b255ae2ebc8dcf
  size: 56123695
haproxy/haproxy-1.5-dev19.tar.gz:
  object_id: 62e4f1aa-4f9f-4a37-b5d3-a5382f641a88
  sha: 5c16686c516dbeaab8ada6c17c25e9629ab4f7d3
  size: 1143258
util-linux/util-linux_2.20.1.orig.tar.gz:
  object_id: 00358c94-0d4b-4db5-bb8f-f8b6df178818
  sha: d1dcff8d39e1a821cb0efda31a38452d12fd6b52
  size: 6174190
java/jre1.8.0_20.tar.gz:
  object_id: 49264d83-d6a7-4444-a801-88e4af6e0691
  sha: 30745df3fca966a222a2800052aa2406ad987de3
  size: 62751094
cf-cli/cf-linux-amd64-6.10.tgz:
  object_id: cda6b19b-8df2-4583-a1b5-a0ab78ba191d
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 41da4b88-799e-4d52-bdf0-a0597bffc35a
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
rabbitmq-server/rabbitmq-server-generic-unix-3.5.6.tar.gz:
  object_id: 662b37f2-423c-4326-95dc-3c13751c6252
  sha: 54cb9039f12bcea93baae73f9a66de3b6f607305
  size: 4216909
rabbitmq-server/rabbitmq_clusterer-3.5.6.ez:
  object_id: 266b0f34-871f-4b3a-9524-3305e97bbc68
  sha: c2d263b8dab2544ba9a5ce4cab326a3801073102
  size: 57463
erlang/otp_src_18.1.tar.gz:
  object_id: 0e56d3c4-78d4-45d1-8254-9f31f63d1b10
  sha: 99361cb597548298cb14b104ebafa4e5a40ff442
  size: 68231709
