---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang-20/otp_src_oss_20.3.8.23.tgz:
  size: 54687816
  object_id: 52ff0e68-5df2-488d-6e13-ff71010caf40
  sha: sha256:b80e128e137843fcfd9eee44d7efb1fdab4307e769b725c6d5b412c31d1a119b
erlang-21/otp_src_oss_21.3.8.10.tgz:
  size: 55217381
  object_id: c3224b35-0a54-4458-70c9-9f8df2a6b6c8
  sha: sha256:49d87375a0b85d859610844160dd6c8c0b5b6c203c63c8d2e0dab0b2bdd63984
erlang-22/otp_src_oss_22.1.3.tgz:
  size: 56207643
  object_id: 1e00ea0a-8c68-4edf-4d22-952caaf0de4b
  sha: sha256:f0189aa943ddcc336067bb7084695afc01f6ed7282f64f7dc2ad46b35dc781e5
golang/go1.13.3.linux-amd64.tar.gz:
  size: 120055279
  object_id: a9cb86f5-e68b-44de-6b5b-eeb3a347aa23
  sha: sha256:0804bf02020dceaa8a7d7275ee79f7a142f1996bfd0c39216ccb405f93f994c0
haproxy/haproxy-1.8.21.tar.gz:
  size: 2097089
  object_id: 10adb602-7a48-4636-7891-87fd6eb966e1
  sha: sha256:34bc80bbaab6edae80add1e8b321636e50ccc56cb583040d98d5d245570680e1
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.18.tar.xz:
  size: 10044888
  object_id: 15fab99f-434c-40df-4e75-db7418438460
  sha: sha256:30a8439671f44f0fc9611782fdfaabba5c1773da85fca279e2850ad28442a2d5
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.0.tar.xz:
  size: 11588100
  object_id: 4d3012ea-f9e7-484a-7a84-d05c57a9d7f0
  sha: sha256:821e7f5312b1386a00a026d594523b026b2114d3b353d4458a829c7f1a35fa0d
