---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_20.3.8.20.tgz:
  size: 54669608
  object_id: a9bf7e36-b3ca-4536-7bca-91bfcd460278
  sha: sha256:8e3be4da902706d713ca056e653d1d5149201a0cc5f11e79a28c3653ff4ad448
golang/go1.12.linux-amd64.tar.gz:
  size: 127228112
  object_id: 7b85ee14-c5f0-4f20-5b60-57c88fdc7ba5
  sha: sha256:750a07fef8579ae4839458701f4df690e0b20b8bcce33b437e4df89c451b6f13
haproxy/haproxy-1.8.19.tar.gz:
  size: 2080757
  object_id: 2ec3d7bf-870e-4c49-6b57-3c058642f349
  sha: sha256:64f5fbfd4e09ffeaf26cb6667398ba780704a14e96e60000caa8bf69962ba734
rabbitmq-server-3.6/rabbitmq-server-generic-unix-3.6.16.tar.xz:
  size: 4808464
  object_id: b9575b38-5483-44bb-4c4a-58de00155fb5
  sha: sha256:d7b0a5dbe670a79da7895b0dea6ccc74e778c3d309b6f7116e8ee4e2bd796b20
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.12.tar.xz:
  size: 9448920
  object_id: '09f9e096-a54b-4d88-5e16-2d478cfdc5f8'
  sha: sha256:71238df9215d399e6e16bad05b19667bd9c9413526370b8e2e7606c923e14a60
