---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang-20/otp_src_oss_20.3.8.23.tgz:
  size: 54687816
  object_id: 52ff0e68-5df2-488d-6e13-ff71010caf40
  sha: sha256:b80e128e137843fcfd9eee44d7efb1fdab4307e769b725c6d5b412c31d1a119b
erlang-21/otp_src_oss_21.3.8.8.tgz:
  size: 55214764
  object_id: e0d56d2d-daca-4288-77cd-2d5072d03f22
  sha: sha256:8d3c90cd805344318d91ad6879c44ada372ccf346d556e5ad9676bbd73213496
erlang-22/otp_src_oss_22.1.2.tgz:
  size: 56204541
  object_id: 98581e58-f427-461e-5c90-853628ca91a7
  sha: sha256:f2a5b373d6f996e38bb42cb654d9500643b2d8c6c5e568b581760c79f761db07
golang/go1.13.1.linux-amd64.tar.gz:
  size: 120040373
  object_id: 0b56091e-f1bd-4626-65e6-d7eff6e193bf
  sha: sha256:94f874037b82ea5353f4061e543681a0e79657f787437974214629af8407d124
haproxy/haproxy-1.8.21.tar.gz:
  size: 2097089
  object_id: 10adb602-7a48-4636-7891-87fd6eb966e1
  sha: sha256:34bc80bbaab6edae80add1e8b321636e50ccc56cb583040d98d5d245570680e1
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.18.tar.xz:
  size: 10044888
  object_id: 15fab99f-434c-40df-4e75-db7418438460
  sha: sha256:30a8439671f44f0fc9611782fdfaabba5c1773da85fca279e2850ad28442a2d5
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.0-rc.3.tar.xz:
  size: 11590652
  object_id: 23897c5a-4219-4d0f-5a7b-913cb4dc1530
  sha: sha256:30650c6ab6759ff00c3c625f79e21f300fce9a2484c0f255dd9000f7d2e55517
