---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-21/otp_src_oss_21.3.8.13.tgz:
  size: 55632180
  object_id: 378cba6d-0123-4fcf-6ef9-b4e614be1a0f
  sha: sha256:c3196f6c697997337a96fe7ddeb4b6a3c01345e947f97653587a5f82d24a24fc
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.2.8.tgz:
  size: 57431063
  object_id: 900e9000-a9f3-40b6-600f-41b96e0c5ce4
  sha: sha256:1b5afcad1967cd2fc91e17165aa52c35f9cecccc5d62329252c263e7f6263232
# this comment prevents git conflicts
golang/go1.13.8.linux-amd64.tar.gz:
  size: 120075156
  object_id: d79beeaa-e0dc-4558-65b0-248a7a327ece
  sha: sha256:0567734d558aef19112f2b2873caa0c600f1b4a5827930eb5a7f35235219e9d8
# this comment prevents git conflicts
haproxy/haproxy-1.8.24.tar.gz:
  size: 2178823
  object_id: cb74ba09-a3f6-4689-67bb-d2a3a8852180
  sha: sha256:da4bc3db58105f2016a706b5c0242a6c870266c69581146ac7c363210604771a
# this comment prevents git conflicts
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.24.tar.xz:
  size: 10059652
  object_id: a81b6146-7ec9-4281-5d31-49b79dfc71e6
  sha: sha256:9c40440a2b66ca352c8d329acca1268a279729e7e237db1087291dad9400918a
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.2.tar.xz:
  size: 11642480
  object_id: bdf99c83-5a56-4adf-6f6b-6f7a0c3c9ed2
  sha: sha256:e403744f23d0b336c177a17f843f7172dfb8b93b2866f34756dd0e404848b85b
