---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.4.6.tgz:
  size: 60006884
  object_id: 9525829d-69f3-4069-4647-6ba33dd2ffb8
  sha: sha256:684a9a18e4e5bac172b639b4ba71c321774cfc16d9416a3a416bdf0a1ed23532
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.1.2.tgz:
  size: 60424672
  object_id: 0d82d21b-8803-4f35-5a40-3ec9b9dd70f2
  sha: sha256:1b32f31c2c2f78b63b8812a6076c12c6a9d6f1d283b1eee5c220eeedeaee5dff
# this comment prevents git conflicts
golang/go1.19.4.linux-amd64.tar.gz:
  size: 148931745
  object_id: 367db67f-efcf-43d9-43a4-77a9b7dfa322
  sha: sha256:c9c08f783325c4cf840a94333159cc937f05f75d36a8b307951d5bd959cf2ab8
# this comment prevents git conflicts
haproxy/haproxy-2.6.7.tar.gz:
  size: 4028355
  object_id: 9b152d3f-f64a-461b-4aa4-5030ef5326ad
  sha: sha256:cff9b8b18a52bfec277f9c1887fac93c18e1b9f3eff48892255a7c6e64528b7d
# this comment prevents git conflicts
openssl/openssl-1.1.1s.tar.gz:
  size: 9868981
  object_id: cb0b36e0-f99e-4f26-405a-afa944d30a02
  sha: sha256:c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.35.tar.xz:
  size: 15825620
  object_id: 7442d589-7af9-4353-5737-e396ad7551ed
  sha: sha256:09c970742b84209af5fe7e8f38ad8eaa9d074b798056bbe7dc83a7a32df3d9af
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.27.tar.xz:
  size: 14779428
  object_id: 68c7dfb5-9553-4036-4bcb-307ad2b91ae2
  sha: sha256:dc6ff9f39e3d335d6705305d7442d24da278cfc573dc313e896518749a636396
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.12.tar.xz:
  size: 14880764
  object_id: 1937c67b-66a0-4b9f-47c9-12563ab0c5df
  sha: sha256:d75e6f293a2fd33ca39722462923e0b4757eed8f5cc5333f0b3edf01145a53ce
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.4.tar.xz:
  size: 15288836
  object_id: 9240e58a-54a3-4cda-6237-fbb8fd6b33c2
  sha: sha256:a171f4683ced80b631ce9c137e15588a9cc271954bc42b8a18ddbf39dc59f3a1
