---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.2.7.tgz:
  size: 62888086
  object_id: 8ea3fcb8-5790-42e1-739d-edda47f44d99
  sha: sha256:77ac1d9745163a0dff368a646ecf14511818b27f759b521ed4afbff7635808bc
# this comment prevents git conflicts
erlang-26/otp_src_oss_26.2.tgz:
  size: 64515029
  object_id: ce0462e9-7089-43dd-59fe-fa0377d46c0b
  sha: sha256:e44cc77016f1a67592b514e5c0e717f4270b24d020fff67eec6a38a610e06b6c
# this comment prevents git conflicts
golang/go1.21.5.linux-amd64.tar.gz:
  size: 66618285
  object_id: 85d5a5fe-1211-4063-6807-9817b54d7316
  sha: sha256:e2bc0b3e4b64111ec117295c088bde5f00eeed1567999ff77bc859d7df70078e
# this comment prevents git conflicts
haproxy/haproxy-2.6.16.tar.gz:
  size: 4084854
  object_id: f78310f9-c327-4682-7051-e76e94208dae
  sha: sha256:faac6f9564caf6e106fe22c77a1fb35406afc8cd484c35c2c844aaf0d7a097fb
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.25.tar.xz:
  size: 15006512
  object_id: 4e0309e6-bdab-4342-57da-368f5d6ba685
  sha: sha256:5a915280dc6d521de9403a07e42d66ea9e3bf7d24880b356d395b950e6dcb3ca
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.27.tar.xz:
  size: 15594724
  object_id: f16c1dc0-dd1f-4abc-77db-62e85cddad4e
  sha: sha256:d56511e710a6fcad753fcda64fc3f93151e26a0f29694305907117063a8bce8e
# this comment prevents git conflicts
rabbitmq-server-3.12/rabbitmq-server-generic-unix-3.12.10.tar.xz:
  size: 15671120
  object_id: 93d1b5f2-bc37-4eb4-5ba9-6371577a7bf7
  sha: sha256:cf79a3ae875f3dea23e865f52dbf205f9a98312e98e0836af41aa422752f8f47
