---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_20.3.8.21.tgz:
  size: 54685824
  object_id: 53df593e-698c-469a-4ae3-6459a34d37cf
  sha: sha256:34788e6de7e7c1c76decfa51f10d2217e0b5ae30c3b3e6cc117baf3e77463dac
golang/go1.11.5.linux-amd64.tar.gz:
  size: 140132627
  object_id: 4cf41b9a-acf4-4f00-4f78-c6c95a4b074b
  sha: sha256:ff54aafedff961eb94792487e827515da683d61a5f9482f668008832631e5d25
haproxy/haproxy-1.8.20.tar.gz:
  size: 2083917
  object_id: 71408931-a167-4faa-623d-d5759178cf59
  sha: sha256:3228f78d5fe1dfbaccf41bf387e36b08eeef6e16330053cafde5fa303e262b16
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.14.tar.xz:
  size: 9492032
  object_id: a30cbc6f-787b-4f9c-4b4a-0b36f2776701
  sha: sha256:f036f3abb4c37f1dbaa62042e2358b255a535e4c04b3a573d2e2e991748411c3
