---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.1.tgz:
  size: 60511056
  object_id: 463d90da-0a28-41ce-6c56-d4d98168a634
  sha: sha256:bf90c912722247f60b26d7cd8a8c1aaaf7e590a7a0ce7b62058ae51d04d3eb29
# this comment prevents git conflicts
golang/go1.20.3.linux-amd64.tar.gz:
  size: 100142274
  object_id: 5fc6c6b8-a758-42d7-67ac-24b191d4dc12
  sha: sha256:979694c2c25c735755bf26f4f45e19e64e4811d661dd07b8c010f7a8e18adfca
# this comment prevents git conflicts
haproxy/haproxy-2.6.13.tar.gz:
  size: 4065839
  object_id: 759eebd7-e614-46ec-6af0-0a9ba76f50fc
  sha: sha256:d69ff5233dbca657132ef280d111222ec1e33f5be1c1937d4e9ff516f63f5243
# this comment prevents git conflicts
openssl/openssl-1.1.1t.tar.gz:
  size: 9881866
  object_id: 41ea1132-9cbb-4b9f-5ce6-de9ad34639d1
  sha: sha256:8dee9b24bdb1dcbf0c3d1e9b02fb8f6bf22165e807f45adeb7c9677536859d3b
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.20.tar.xz:
  size: 20416496
  object_id: 3b087b20-cd20-4a1c-4961-b3f7ff191bea
  sha: sha256:920ad374db2f3db05976fe859a819ab15e51170fae414468c08b8781eea3d38f
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.13.tar.xz:
  size: 20876804
  object_id: e773d3bb-eac8-4863-463d-94c5afdfed07
  sha: sha256:02d3e7aed9085a288a94ad978624944038b9b5958d5c9bdeade09aa806fd50e7
