---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss-20.3.5.tgz:
  size: 55547853
  sha: 5ee59e279e443a5cf4d5758303c26dfe6c586504
golang/go1.10.2.linux-amd64.tar.gz:
  size: 132481801
  object_id: ed7dc9dc-8d6c-4562-7f25-630ff5a2eacc
  sha: sha256:4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
haproxy/haproxy-1.6.13.tar.gz:
  size: 1580214
  object_id: 84b3dd36-e9f7-4917-aa31-67798f94975a
  sha: ae0cabea33c718b08d463016248facd31a3618b8
rabbitmq-server-3.6/rabbitmq-server-generic-unix-3.6.15.tar.xz:
  size: 4799688
  object_id: be19e3a4-a491-4b6c-455a-711e979a0dec
  sha: c452469bfc6982a79271aedc529d41e0ed16366e
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.4.tar.xz:
  size: 11484844
  object_id: 3ea2c00b-d59b-44d5-42ea-d3f253e0991a
  sha: 131b55207698b12d109b935db16e3f85e1b06540
