---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_20.3.8.11.tgz:
  size: 54661798
  object_id: e05c5103-34b3-443c-5e51-402ce5b902e4
  sha: sha256:a6698a5a75c71f6e9bb6fdf3382cca7f8de77614ff7bea68e5f545eff0201a79
golang/go1.10.4.linux-amd64.tar.gz:
  size: 92794622
  object_id: 642462fd-ee41-4461-71f8-223c3bd3a0a3
  sha: sha256:fa04efdb17a275a0c6e137f969a1c4eb878939e91e1da16060ce42f02c2ec5ec
haproxy/haproxy-1.6.13.tar.gz:
  size: 1580214
  object_id: 84b3dd36-e9f7-4917-aa31-67798f94975a
  sha: ae0cabea33c718b08d463016248facd31a3618b8
rabbitmq-server-3.6/rabbitmq-server-generic-unix-3.6.16.tar.xz:
  size: 4808464
  object_id: b9575b38-5483-44bb-4c4a-58de00155fb5
  sha: sha256:d7b0a5dbe670a79da7895b0dea6ccc74e778c3d309b6f7116e8ee4e2bd796b20
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.9.tar.xz:
  size: 9200564
  object_id: 560b5d50-0415-486e-7975-c7ff4eabe1ba
  sha: sha256:43214e32316ce4eb6a0a0013b897b2a0c7c96d6814ba6bd01ae60032e8c2479f
