---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-21/otp_src_oss_21.3.8.14.tgz:
  size: 55634927
  object_id: 2adf93a3-a299-4442-48f1-0f5aae7dbd96
  sha: sha256:f834fe256c8abb9ccfa5962cd651c2fa75bc5a1fe1016804e033c0538341e0b6
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.tgz:
  size: 57501916
  object_id: c894deb7-920e-4a0b-4dbb-4755f9be9745
  sha: sha256:2c784faa2d4143ad89b6bba3ef7a43dad93eae9e4e9dc26dc6282d0527a2d8ae
# this comment prevents git conflicts
golang/go1.14.linux-amd64.tar.gz:
  size: 123550266
  object_id: 03670322-1fa4-437c-467c-8a8fa4cd2da1
  sha: sha256:08df79b46b0adf498ea9f320a0f23d6ec59e9003660b4c9c1ce8e5e2c6f823ca
# this comment prevents git conflicts
haproxy/haproxy-1.8.24.tar.gz:
  size: 2178823
  object_id: cb74ba09-a3f6-4689-67bb-d2a3a8852180
  sha: sha256:da4bc3db58105f2016a706b5c0242a6c870266c69581146ac7c363210604771a
# this comment prevents git conflicts
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.24.tar.xz:
  size: 10059652
  object_id: a81b6146-7ec9-4281-5d31-49b79dfc71e6
  sha: sha256:9c40440a2b66ca352c8d329acca1268a279729e7e237db1087291dad9400918a
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.3.tar.xz:
  size: 11958032
  object_id: b8cef8eb-5090-4462-7b52-93a19be01789
  sha: sha256:5a2739ed1dba77f88316b4c63393d8037fc4acf51881ba922470453e891875b6
