---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.2.5.tgz:
  size: 58298090
  object_id: fa323339-53aa-43b7-4166-dbaa55a422c5
  sha: sha256:883dcfa8b9f7c337720f9e67bc4a64d2396cf2846831fde9de9c109e5c0f2d42
# this comment prevents git conflicts
golang/go1.16.linux-amd64.tar.gz:
  size: 129003129
  object_id: c2540b31-9d33-4d61-64da-746efdbf1887
  sha: sha256:013a489ebb3e24ef3d915abe5b94c3286c070dfe0818d5bca8108f1d6e8440d2
# this comment prevents git conflicts
haproxy/haproxy-1.8.28.tar.gz:
  size: 2211162
  object_id: 3172c51f-6cb5-4b67-5215-f3a909b7f2c0
  sha: sha256:fecf031486014d5838499f69cba0348abffa076e55f6fadf86a8da93cbf94e89
# this comment prevents git conflicts
openssl/openssl-1.1.1i.tar.gz:
  size: 9808346
  object_id: ee07e0f6-bc01-48d7-496b-c1516e6e1f0c
  sha: sha256:e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.11.tar.xz:
  size: 15644332
  object_id: 59ce2d8a-73b4-49a3-5045-e586d0096b73
  sha: sha256:05b05305fc4f598907ef5e3ec552ae610e0db80f7a03b3fb842699c5b7bf6822
