---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.3.tgz:
  size: 57521606
  object_id: 93fc2bf0-4155-4f9a-7473-375bbc6de8d8
  sha: sha256:e5c014e8e5268d6c1dc14e7160cfed2a84c0e51251510e419bcf212b70680c36
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.0.3.tgz:
  size: 58083053
  object_id: 1f6cb181-8537-40bf-5ece-6d7167e181c2
  sha: sha256:f3969d1fde42e0f5761876e8e7081860e844c2cb632b100e0145f79f4855a645
# this comment prevents git conflicts
golang/go1.14.6.linux-amd64.tar.gz:
  size: 123744187
  object_id: 1cf680cb-2dc6-4dc0-7a8f-c5f9117682f4
  sha: sha256:5c566ddc2e0bcfc25c26a5dc44a440fcc0177f7350c1f01952b34d5989a0d287
# this comment prevents git conflicts
haproxy/haproxy-1.8.25.tar.gz:
  size: 2184002
  object_id: 47b0cf98-47e9-4c26-7aca-17f010ea99e4
  sha: sha256:62c0b77de2275a54a443a869947ddcca2bad7bdc1cafd804732a0e0d59b1708b
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.6.tar.xz:
  size: 15254960
  object_id: 4c286460-b673-4443-5c10-66f4cf0c17a5
  sha: sha256:51f8013881d7965134e8fbba2c23c93d64f9b3279e4eedbcccfb493a5146eac4
