---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.3.2.tgz:
  size: 58371496
  object_id: 2c13eedf-db7f-4fc6-4f6f-384f3d176346
  sha: sha256:e361cb46553e9a7b54bfcbef0943d75d9344389e6bb94d83f4f30fd7189d8da2
# this comment prevents git conflicts
golang/go1.16.3.linux-amd64.tar.gz:
  size: 129021323
  object_id: eb41ccb1-e15c-4d88-559f-8e69a9efecc8
  sha: sha256:951a3c7c6ce4e56ad883f97d9db74d3d6d80d5fec77455c6ada6c1f7ac4776d2
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1k.tar.gz:
  size: 9823400
  object_id: e673f8f5-6f15-4cf6-5531-dff668da58b3
  sha: sha256:892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.15.tar.xz:
  size: 15583200
  object_id: c9623366-a501-4756-69bb-c56c791501f4
  sha: sha256:9e1a3f89e9baffd03bd672a8342aebc778425da116f36a6acbb8869cdcd939d2
