---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.2.1.tgz:
  size: 58283174
  object_id: c9484dd7-87ad-4cc1-59c4-92d628caf0a1
  sha: sha256:e42c9743b14c585f86566af2a21c8a26cd80175462b3c5f52b61bcaab0af90eb
# this comment prevents git conflicts
golang/go1.15.7.linux-amd64.tar.gz:
  size: 121031670
  object_id: 5b3d251c-67c4-4e50-4272-c1efe0ea2020
  sha: sha256:0d142143794721bb63ce6c8a6180c4062bcf8ef4715e7d6d6609f3a8282629b3
# this comment prevents git conflicts
haproxy/haproxy-1.8.28.tar.gz:
  size: 2211162
  object_id: 3172c51f-6cb5-4b67-5215-f3a909b7f2c0
  sha: sha256:fecf031486014d5838499f69cba0348abffa076e55f6fadf86a8da93cbf94e89
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.9.tar.xz:
  size: 15361208
  object_id: 1ba9d053-add9-4719-522e-55d0d5cc76aa
  sha: sha256:fe1f1ef9b1bd8362421d689ec9b73cb33c8aaf96acf990df6549e3c0275b7aa0
