---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.4.tgz:
  size: 59753916
  object_id: e334e961-9451-42e2-7e99-ece936daf710
  sha: sha256:7ad08a7af0611884562334386de9f0b41024b615b84e1d4dca7d67da684009fe
# this comment prevents git conflicts
golang/go1.18.3.linux-amd64.tar.gz:
  size: 141748419
  object_id: 5dd05ab4-d2e6-40f5-7488-426e70325384
  sha: sha256:956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 28c64cdd-00ef-4027-4afb-e1b11d8acfa9
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.33.tar.xz:
  size: 15838432
  object_id: 8bc81940-7e1b-4f67-4980-4dd3d70dda08
  sha: sha256:7996cc1c77b096681c7bc61d4827a379c53e24fd9ec86dc90c43fa359bf77de0
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.20.tar.xz:
  size: 12749544
  object_id: d2ce3333-812a-4b1f-41a3-b7f7c18cf7c3
  sha: sha256:f5e24d3af14d9e52bb461cd4d52336254472fd67cf9b4cb06ffbb4e381abac9b
