---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.3.tgz:
  size: 57521606
  object_id: 93fc2bf0-4155-4f9a-7473-375bbc6de8d8
  sha: sha256:e5c014e8e5268d6c1dc14e7160cfed2a84c0e51251510e419bcf212b70680c36
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.0.3.tgz:
  size: 58083053
  object_id: 1f6cb181-8537-40bf-5ece-6d7167e181c2
  sha: sha256:f3969d1fde42e0f5761876e8e7081860e844c2cb632b100e0145f79f4855a645
# this comment prevents git conflicts
golang/go1.15.1.linux-amd64.tar.gz:
  size: 121150330
  object_id: bda2f34d-34f1-46d3-64b4-7a00669eaf6c
  sha: sha256:70ac0dbf60a8ee9236f337ed0daa7a4c3b98f6186d4497826f68e97c0c0413f6
# this comment prevents git conflicts
haproxy/haproxy-1.8.26.tar.gz:
  size: 2205531
  object_id: 4adf741e-574f-4947-5f40-ed94cb95aa77
  sha: sha256:e3c2a81b6f26dcb736a34ebb5f134d3251ceccf30386214655fa7ed6d3afa400
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.7.tar.xz:
  size: 15253020
  object_id: c22d8fff-cdaf-4cd6-4dac-50ee1c8cc2f7
  sha: sha256:7b36e4d3e9359185d9da477b68f01d07321288288bcc45198f4ffe0242d76287
