---
erlang/otp_src_oss_18.1.tgz:
  object_id: 6cf4831f-727d-44b5-9cd2-1bb33c25b4c5
  sha: cf5a7e63074a4743e976d87b5f9fe80deac61cfe
  size: 68197399
golang/go1.6.1.linux-amd64.tar.gz:
  object_id: 6483bb0d-c45f-4b69-a732-d4cac4f88cc7
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
haproxy/haproxy-1.6.4.tar.gz:
  object_id: f790a114-2611-4f78-8bf7-99f714c268d8
  sha: df3d7f216fe4974d9eac55d76c7f729560c6e975
  size: 1559276
java/jre-1.8.0_77.tar.gz:
  object_id: f9f7a230-63e5-4eae-857f-fcb849966cc9
  sha: 8edb2189ef42d6756faa355efeb356aead6e6da3
  size: 71796315
cf-cli/cf-cli_6.19.0_linux_x86-64.tgz:
  object_id: 22ad54c4-568e-4ca3-aa73-12b691e3f678
  sha: 625170654ffa4568dae97b4d3915e87557b29261
  size: 6450885
rabbitmq-server/rabbitmq-server-generic-unix-3.6.5.906.tar.xz:
  object_id: 1f202f4b-dd9e-4ce6-9241-53d677f93031
  sha: 5040014e4b1ab6c0240f73085849a7d9fb518b19
  size: 5282688
rabbitmq-server/rabbitmq_clusterer-3.6.5.906.ez:
  object_id: 82b023cd-ec3c-4d14-90cc-7ea6263b7a82
  sha: 1b68e7ca22ca0c90662d89e1eed3a4683aebdd85
  size: 57475
