---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-21/otp_src_oss_21.3.8.10.tgz:
  size: 55217381
  object_id: c3224b35-0a54-4458-70c9-9f8df2a6b6c8
  sha: sha256:49d87375a0b85d859610844160dd6c8c0b5b6c203c63c8d2e0dab0b2bdd63984
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.1.6.tgz:
  size: 56218510
  object_id: 344cb3fb-7ba2-49b5-563c-58f8ca956a60
  sha: sha256:ba6fa528569d17aa46835728b5f6196a6718d6ed515723b00799cc97e10ed608
# this comment prevents git conflicts
golang/go1.13.4.linux-amd64.tar.gz:
  size: 120054682
  object_id: badf2520-20b7-4290-47bc-52ab4407d3f0
  sha: sha256:692d17071736f74be04a72a06dab9cac1cd759377bd85316e52b2227604c004c
# this comment prevents git conflicts
haproxy/haproxy-1.8.22.tar.gz:
  size: 2100471
  object_id: 146b3d07-897f-44b9-6ad8-59ce5bff0551
  sha: sha256:7be245cdbc3fff9365af1df1c13fdff768fb7f9c4363e7daa52c315ec20dc1f8
# this comment prevents git conflicts
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.20.tar.xz:
  size: 10051972
  object_id: 5acbc636-15de-4196-7a75-5602358c039c
  sha: sha256:4db50b4587fc0cd8b1c15752efa3f72f78527a14a60fd9133be7a629a0249800
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.0.tar.xz:
  size: 11588100
  object_id: 4d3012ea-f9e7-484a-7a84-d05c57a9d7f0
  sha: sha256:821e7f5312b1386a00a026d594523b026b2114d3b353d4458a829c7f1a35fa0d
