---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.4.6.tgz:
  size: 60006884
  object_id: 9525829d-69f3-4069-4647-6ba33dd2ffb8
  sha: sha256:684a9a18e4e5bac172b639b4ba71c321774cfc16d9416a3a416bdf0a1ed23532
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.1.2.tgz:
  size: 60424672
  object_id: 0d82d21b-8803-4f35-5a40-3ec9b9dd70f2
  sha: sha256:1b32f31c2c2f78b63b8812a6076c12c6a9d6f1d283b1eee5c220eeedeaee5dff
# this comment prevents git conflicts
golang/go1.19.3.linux-amd64.tar.gz:
  size: 148907134
  object_id: 598fbda1-6d6c-4f1e-4b4c-735ae0b0eb29
  sha: sha256:74b9640724fd4e6bb0ed2a1bc44ae813a03f1e72a4c76253e2d5c015494430ba
# this comment prevents git conflicts
haproxy/haproxy-2.6.6.tar.gz:
  size: 4015438
  object_id: 8b650d8e-9e67-4250-54b9-9b8c388edc8a
  sha: sha256:d0c80c90c04ae79598b58b9749d53787f00f7b515175e7d8203f2796e6a6594d
# this comment prevents git conflicts
openssl/openssl-1.1.1s.tar.gz:
  size: 9868981
  object_id: cb0b36e0-f99e-4f26-405a-afa944d30a02
  sha: sha256:c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.35.tar.xz:
  size: 15825620
  object_id: 7442d589-7af9-4353-5737-e396ad7551ed
  sha: sha256:09c970742b84209af5fe7e8f38ad8eaa9d074b798056bbe7dc83a7a32df3d9af
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.24.tar.xz:
  size: 14771336
  object_id: 38a88643-853b-4678-4f6b-09d5fe730886
  sha: sha256:d48d4c9129089fd7c464b200d4f2077493b55bdceff772b1b42c21c8e8ffa76d
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.11.tar.xz:
  size: 14879284
  object_id: 4ec3f354-380d-493a-4819-c895f7b6c5dc
  sha: sha256:5743b3e8326f444c47323fb9805f318dc94a1ac95b8e79c20237390776971f50
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.3.tar.xz:
  size: 15277924
  object_id: 0fe5d151-1056-48a9-56c0-e697930cfb4c
  sha: sha256:8006e6f95462f2c6b01205d2a6913dcbc8424a55d7f58579aec1f8f0c6cfa228
