---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.4.2.tgz:
  size: 59954332
  object_id: fb29865b-86f4-48da-6d63-e6593e49ac90
  sha: sha256:03354d2aa12e257a6777cbcda365cb69d2fc4fdade1988755ad3f3c94c4a5f93
# this comment prevents git conflicts
golang/go1.18.3.linux-amd64.tar.gz:
  size: 141748419
  object_id: 5dd05ab4-d2e6-40f5-7488-426e70325384
  sha: sha256:956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1q.tar.gz:
  size: 9864061
  object_id: f6b64f54-3a96-46e0-6488-4ffb05fbc50f
  sha: sha256:d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.34.tar.xz:
  size: 15836896
  object_id: 2f8d19b7-70d4-4a85-4d28-f71204f5c643
  sha: sha256:067e19296e245635c2d7ae5aad6029a6d0a9264fded66414b922f0a66eeb6d23
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.21.tar.xz:
  size: 12759484
  object_id: 44a0c51e-be33-4d0c-41c1-efb7b594f4fa
  sha: sha256:b0cd6af2ea53f4b56c130d1668acb161565b619bb5cc9d67f458b1ba88ce444b
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.5.tar.xz:
  size: 12792748
  object_id: 1b886eb5-3a8f-47c8-4f6a-00061e3093b0
  sha: sha256:4e90dab6932161f4760a6b8b4ede29fc45002839134985043cca8214184ca859
