---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang-21/otp_src_oss_21.3.8.10.tgz:
  size: 55217381
  object_id: c3224b35-0a54-4458-70c9-9f8df2a6b6c8
  sha: sha256:49d87375a0b85d859610844160dd6c8c0b5b6c203c63c8d2e0dab0b2bdd63984
erlang-22/otp_src_oss_22.1.5.tgz:
  size: 56209144
  object_id: 1435dd40-1d7a-4a2f-4a21-aefddebd3c5d
  sha: sha256:5bb72eebabdbde9ed4946a9d06859857984f3ad1fc31f22efe2cf4df727f41cf
golang/go1.13.4.linux-amd64.tar.gz:
  size: 120054682
  object_id: badf2520-20b7-4290-47bc-52ab4407d3f0
  sha: sha256:692d17071736f74be04a72a06dab9cac1cd759377bd85316e52b2227604c004c
haproxy/haproxy-1.8.22.tar.gz:
  size: 2100471
  object_id: 146b3d07-897f-44b9-6ad8-59ce5bff0551
  sha: sha256:7be245cdbc3fff9365af1df1c13fdff768fb7f9c4363e7daa52c315ec20dc1f8
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.21.tar.xz:
  size: 10054132
  object_id: d047fa20-8e14-4883-67b8-f1e507bb8cd2
  sha: sha256:ef9a944f965393cb16c983d5dd6a7337c6aca77efbe89683e9ef37fab9d421a2
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.1.tar.xz:
  size: 11630708
  object_id: 01753dba-cd3c-402a-6c77-d646792c5975
  sha: sha256:a21f012ba71dfe192763aad1384388b8dd0d9907ae61ce6d0b3055d47dcf336e
