---
erlang/otp_src_17.1.tar.gz:
  object_id: 75128d78-5cb1-4892-80db-111d80033084
  sha: 3f5756c6ea4a6af5240412250224bd6e1c774f55
  size: 66912681
golang/go1.2.1.linux-amd64.tar.gz:
  object_id: c87bdd9b-8d34-43cc-b84c-bb3c493a1026
  sha: 7605f577ff6ac2d608a3a4e829b255ae2ebc8dcf
  size: 56123695
haproxy/haproxy-1.5-dev19.tar.gz:
  object_id: 62e4f1aa-4f9f-4a37-b5d3-a5382f641a88
  sha: 5c16686c516dbeaab8ada6c17c25e9629ab4f7d3
  size: 1143258
util-linux/util-linux_2.20.1.orig.tar.gz:
  object_id: 00358c94-0d4b-4db5-bb8f-f8b6df178818
  sha: d1dcff8d39e1a821cb0efda31a38452d12fd6b52
  size: 6174190
rabbitmq-server/rabbitmq-server-generic-unix-3.4.3.1.tar.gz:
  object_id: 7528f400-54c8-4d88-8ab9-eb1ccd0fdf4e
  sha: 4b286cc5c3b87538f61ddd14a1dbe8e2ed279b8b
  size: 4611705
rabbitmq-server/rabbitmq_clusterer-3.4.3.1.ez:
  object_id: e4904636-e027-436f-a8dd-4f4ae680a728
  sha: 8d002615d66af2498ef922507957d5cf6274489d
  size: 57318
java/jre1.8.0_20.tar.gz:
  object_id: 49264d83-d6a7-4444-a801-88e4af6e0691
  sha: 30745df3fca966a222a2800052aa2406ad987de3
  size: 62751094
cf-cli/cf-linux-amd64-6.10.tgz:
  object_id: cda6b19b-8df2-4583-a1b5-a0ab78ba191d
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
