---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.tgz:
  size: 60503085
  object_id: 9749e982-cf54-4607-7a58-e1772f476a3a
  sha: sha256:d4e1be1808f4fd7621bbda46add9dc9ccd62d58a9969a1a279ad21d30abdc4cc
# this comment prevents git conflicts
golang/go1.20.1.linux-amd64.tar.gz:
  size: 99886974
  object_id: 6a8df097-9774-49d6-4064-572e38740dd1
  sha: sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02
# this comment prevents git conflicts
haproxy/haproxy-2.6.10.tar.gz:
  size: 4056147
  object_id: 6cea0c0e-0d26-46d1-415e-4536c2214c18
  sha: sha256:e71b2cd9ca1043345f083a5225078ccf824dced2b5779d86f11fa4e88f451773
# this comment prevents git conflicts
openssl/openssl-1.1.1t.tar.gz:
  size: 9881866
  object_id: 41ea1132-9cbb-4b9f-5ce6-de9ad34639d1
  sha: sha256:8dee9b24bdb1dcbf0c3d1e9b02fb8f6bf22165e807f45adeb7c9677536859d3b
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.19.tar.xz:
  size: 14958132
  object_id: 60f05a55-ea8b-484d-5a07-3829a99cfab4
  sha: sha256:732c98a9ba727f609f5247bf02e36925c439d2615624a59001b4ae5dd80de906
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.10.tar.xz:
  size: 15364720
  object_id: 1a04de0a-8447-48c8-6d1e-dd4eb4b0f757
  sha: sha256:d2aeed2f27e01ae43dd6dd6bacaa30abe3ec1c904fd4c62725c7bac2270eafce
