---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.2.2.tgz:
  size: 58271702
  object_id: 7e0c0c54-7eaf-4bbf-7b41-c015f1fc6efd
  sha: sha256:37787e6e460299f44d0f543d0bbf93812766b93f2d5cebe1826f9ad7dace23e1
# this comment prevents git conflicts
golang/go1.15.6.linux-amd64.tar.gz:
  size: 120951514
  object_id: af371cf6-686c-4df4-5401-86d2ea5b5b2c
  sha: sha256:3918e6cc85e7eaaa6f859f1bdbaac772e7a825b0eb423c63d3ae68b21f84b844
# this comment prevents git conflicts
haproxy/haproxy-1.8.28.tar.gz:
  size: 2211162
  object_id: 3172c51f-6cb5-4b67-5215-f3a909b7f2c0
  sha: sha256:fecf031486014d5838499f69cba0348abffa076e55f6fadf86a8da93cbf94e89
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.10.tar.xz:
  size: 15642444
  object_id: 98b6c4c3-5a5b-47ea-7d00-5c1f6d7807db
  sha: sha256:a07e415986f92291ce2316c8d857eb0392adf5afbe35951943932707d79060be
