---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.3.4.4.tgz:
  size: 57668341
  object_id: 8050c4bc-fd52-4cb7-4d18-986f84960ce0
  sha: sha256:b47a01b67f58ced3359aee5369770aeeb2a4c7c95d43b6b85d044871c02f5658
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.0.2.tgz:
  size: 59327656
  object_id: 236c68b7-6d6d-4c12-7c7b-9f9ca43d2078
  sha: sha256:038350fc4c034418842cbb1568ef8f720226e6faf11f0d80a850f3b047a3db6d
# this comment prevents git conflicts
golang/go1.16.5.linux-amd64.tar.gz:
  size: 129049763
  object_id: 8f27f196-80ea-41b4-5ad7-600f2c7abe63
  sha: sha256:b12c23023b68de22f74c0524f10b753e7b08b1504cb7e417eccebdd3fae49061
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1k.tar.gz:
  size: 9823400
  object_id: e673f8f5-6f15-4cf6-5531-dff668da58b3
  sha: sha256:892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.19.tar.xz:
  size: 15634400
  object_id: f02d9146-2baf-4f8e-72e4-4f1520897371
  sha: sha256:b42d64d6d6738d889054176361093a6795a8e74a273fc3cdf972e01652ec187e
