---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.1.1.tgz:
  size: 58181894
  object_id: eed0bd01-06ab-40f6-60e3-43ae905e584e
  sha: sha256:9207c6670e675b1dc1c25b687a223bcf30c5836a562d95e684f80a397628913c
# this comment prevents git conflicts
golang/go1.15.5.linux-amd64.tar.gz:
  size: 120900442
  object_id: 00eaef06-bae1-43af-6e1c-fda68a29caf6
  sha: sha256:9a58494e8da722c3aef248c9227b0e9c528c7318309827780f16220998180a0d
# this comment prevents git conflicts
haproxy/haproxy-1.8.27.tar.gz:
  size: 2209243
  object_id: c75033fc-c2eb-4b9a-7625-da6d299cad15
  sha: sha256:56ba6a21e13215fae56472ad37d5d68c3f19bde9da94c59e70b869eecf48bf50
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.9.tar.xz:
  size: 15361208
  object_id: 1ba9d053-add9-4719-522e-55d0d5cc76aa
  sha: sha256:fe1f1ef9b1bd8362421d689ec9b73cb33c8aaf96acf990df6549e3c0275b7aa0
