---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.2.9.tgz:
  size: 61373759
  object_id: 58906aa2-1291-4d78-698d-f465b9c6164d
  sha: sha256:3d73152bb58a1cd7411881eb96bfb65b4e21ba3dc75ccd25f66c3816e10256b9
# this comment prevents git conflicts
erlang-26/otp_src_oss_26.2.3.tgz:
  size: 62981316
  object_id: 6ffdabb3-50b2-4ec4-677c-112cbedd7b89
  sha: sha256:adf84ad42f810325d1d2061240a672811701140cc83960a460897b01c06a09d5
# this comment prevents git conflicts
golang/go1.22.2.linux-amd64.tar.gz:
  size: 68958123
  object_id: 7757fbde-6293-4d44-616f-124db7723f69
  sha: sha256:5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17
# this comment prevents git conflicts
haproxy/haproxy-2.6.16.tar.gz:
  size: 4084854
  object_id: f78310f9-c327-4682-7051-e76e94208dae
  sha: sha256:faac6f9564caf6e106fe22c77a1fb35406afc8cd484c35c2c844aaf0d7a097fb
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.28.tar.xz:
  size: 15594916
  object_id: 519ebb39-4f9d-46cf-7d49-7057987bd959
  sha: sha256:7b19ae061454ca1f8aeac0412673f718cb7a9b3a060b495dad0ec6345c3b8f30
# this comment prevents git conflicts
rabbitmq-server-3.12/rabbitmq-server-generic-unix-3.12.13.tar.xz:
  size: 15703612
  object_id: 14c3b8df-aa10-413c-7781-80e61b98b2bf
  sha: sha256:98bc1fee2c961c0a131e6b0e6ff3854f40e80cd40ed7f3daf50828db2437abda
