---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
golang/go1.16.2.linux-amd64.tar.gz:
  size: 129010536
  object_id: 14af4176-e2a1-4375-75ac-e4dc28edbf18
  sha: sha256:542e936b19542e62679766194364f45141fde55169db2d8d01046555ca9eb4b8
# this comment prevents git conflicts
haproxy/haproxy-1.8.29.tar.gz:
  size: 2213262
  object_id: 4c1bcdbd-cd33-4638-439f-5dbbbe219293
  sha: sha256:a91777252bd655413411b832fbce7bb3a27b0484b498e2c614c405e12f53a764
# this comment prevents git conflicts
openssl/openssl-1.1.1k.tar.gz:
  size: 9823400
  object_id: e673f8f5-6f15-4cf6-5531-dff668da58b3
  sha: sha256:892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.14.tar.xz:
  size: 15665332
  object_id: c40886a2-bb9c-4960-646f-78f82087f847
  sha: sha256:c9b154ea42bb0cfd1caef4869cfae3ed0fc3579794dd08bd555057af5736c06e
