---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.3.4.5.tgz:
  size: 57714077
  object_id: 8578bc26-6b23-455e-72ce-f73b71884ddd
  sha: sha256:fd16c147b144198f098c76f66c09dc1fce4a30e4631a14aab1302985cb27c384
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.0.3.tgz:
  size: 59336106
  object_id: 7c646168-7f53-4ceb-58a6-a50eb76d7228
  sha: sha256:806f0413a95d26d8ec62c5fe503b2cb6f288031dfc9ec93bb00f1bf2833a5823
# this comment prevents git conflicts
golang/go1.16.6.linux-amd64.tar.gz:
  size: 129049323
  object_id: 2e90faab-e5d2-45eb-46aa-a9c1607c989b
  sha: sha256:be333ef18b3016e9d7cb7b1ff1fdb0cac800ca0be4cf2290fe613b3d069dfe0d
# this comment prevents git conflicts
haproxy/haproxy-1.8.30.tar.gz:
  size: 2214184
  object_id: 7ce535fa-f17c-4c08-782f-1c24f83287a8
  sha: sha256:066bfd9a0e5a3550fa621886a132379e5331d0c377e11f38bb6e8dfbec92be42
# this comment prevents git conflicts
openssl/openssl-1.1.1k.tar.gz:
  size: 9823400
  object_id: e673f8f5-6f15-4cf6-5531-dff668da58b3
  sha: sha256:892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.19.tar.xz:
  size: 15634400
  object_id: f02d9146-2baf-4f8e-72e4-4f1520897371
  sha: sha256:b42d64d6d6738d889054176361093a6795a8e74a273fc3cdf972e01652ec187e
