---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.2.2.tgz:
  size: 60469841
  object_id: 783d234f-2220-41a7-485f-93c06942ced1
  sha: sha256:0eb9b4945c4168b637fc1816bc0298f9ba7f99a35444347439dbbe382876eed5
# this comment prevents git conflicts
golang/go1.20.linux-amd64.tar.gz:
  size: 99869470
  object_id: bc4a1e0c-8e7b-4ec5-6898-81d28709d621
  sha: sha256:5a9ebcc65c1cce56e0d2dc616aff4c4cedcfbda8cc6f0288cc08cda3b18dcbf1
# this comment prevents git conflicts
haproxy/haproxy-2.6.8.tar.gz:
  size: 4041517
  object_id: 3f0e1f5b-934d-419a-4c1a-a24133a07982
  sha: sha256:a02ad64550dd30a94b25fd0e225ba699649d0c4037bca3b36b20e8e3235bb86f
# this comment prevents git conflicts
openssl/openssl-1.1.1t.tar.gz:
  size: 9881866
  object_id: 41ea1132-9cbb-4b9f-5ce6-de9ad34639d1
  sha: sha256:8dee9b24bdb1dcbf0c3d1e9b02fb8f6bf22165e807f45adeb7c9677536859d3b
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.18.tar.xz:
  size: 14909528
  object_id: 4f17ce2f-8c98-4286-7224-f3fba2e40e90
  sha: sha256:447f802dd39b2f769303841e368563842cf14c0155fd51a791d947bc82b45254
# this comment prevents git conflicts
rabbitmq-server-3.11/rabbitmq-server-generic-unix-3.11.9.tar.xz:
  size: 15360296
  object_id: 40cf86e3-4e24-48ac-4092-7ba70d101ab4
  sha: sha256:bf5e67d1e1460e6f030928f62b3f161a8ca34c0bde421bc5b766c730d991ecd9
