---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-22/otp_src_oss_22.3.4.4.tgz:
  size: 57518837
  object_id: a4c45e98-3852-42ce-6efb-72270bafa43b
  sha: sha256:1d96ef7e9153903c7dfcd7c6714190359fb56d1d2e300840a609145fb63b063a
# this comment prevents git conflicts
erlang-23/otp_src_oss_23.0.3.tgz:
  size: 58083053
  object_id: 1f6cb181-8537-40bf-5ece-6d7167e181c2
  sha: sha256:f3969d1fde42e0f5761876e8e7081860e844c2cb632b100e0145f79f4855a645
# this comment prevents git conflicts
golang/go1.15.1.linux-amd64.tar.gz:
  size: 121150330
  object_id: bda2f34d-34f1-46d3-64b4-7a00669eaf6c
  sha: sha256:70ac0dbf60a8ee9236f337ed0daa7a4c3b98f6186d4497826f68e97c0c0413f6
# this comment prevents git conflicts
haproxy/haproxy-1.8.26.tar.gz:
  size: 2205531
  object_id: 4adf741e-574f-4947-5f40-ed94cb95aa77
  sha: sha256:e3c2a81b6f26dcb736a34ebb5f134d3251ceccf30386214655fa7ed6d3afa400
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.8.tar.xz:
  size: 15350568
  object_id: f47f04a7-2d85-49d6-4086-1a0a739a90db
  sha: sha256:9828d23c709aa36dbf8845313840a47442817c8d4cb4a80065af444d37d08f57
