basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_19.3.6.4.tgz:
  size: 36173300
  object_id: 019636ac-326f-4df7-57b6-80882ce20f6c
  sha: e45a9f1ee0a396207f9691cb703745a9d0ca8de7
golang/go1.9.1.linux-amd64.tar.gz:
  size: 104197862
  object_id: 650b3b65-ba36-4c70-4778-c6ad58b4cacd
  sha: 8ab67607ac917684560e699b76b3121f5799e24e
haproxy/haproxy-1.6.13.tar.gz:
  size: 1580214
  object_id: 84b3dd36-e9f7-4917-aa31-67798f94975a
  sha: ae0cabea33c718b08d463016248facd31a3618b8
rabbitmq-server/rabbitmq-server-generic-unix-3.6.15.tar.xz:
  size: 4799688
  object_id: 213fab4a-cfcd-4263-7936-7410d2678f44
  sha: c452469bfc6982a79271aedc529d41e0ed16366e
