---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-25/otp_src_oss_25.3.1.tgz:
  size: 60511056
  object_id: 463d90da-0a28-41ce-6c56-d4d98168a634
  sha: sha256:bf90c912722247f60b26d7cd8a8c1aaaf7e590a7a0ce7b62058ae51d04d3eb29
# this comment prevents git conflicts
golang/go1.20.4.linux-amd64.tar.gz:
  size: 100148454
  object_id: ad0266f4-f880-4073-5d28-a092af4e1c53
  sha: sha256:698ef3243972a51ddb4028e4a1ac63dc6d60821bf18e59a807e051fee0a385bd
# this comment prevents git conflicts
haproxy/haproxy-2.6.13.tar.gz:
  size: 4065839
  object_id: 759eebd7-e614-46ec-6af0-0a9ba76f50fc
  sha: sha256:d69ff5233dbca657132ef280d111222ec1e33f5be1c1937d4e9ff516f63f5243
# this comment prevents git conflicts
openssl/openssl-1.1.1t.tar.gz:
  size: 9881866
  object_id: 41ea1132-9cbb-4b9f-5ce6-de9ad34639d1
  sha: sha256:8dee9b24bdb1dcbf0c3d1e9b02fb8f6bf22165e807f45adeb7c9677536859d3b
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.22.tar.xz:
  size: 20419340
  object_id: 7483401f-2a46-4f51-73ae-a7fd95ecbbc4
  sha: sha256:4f2b6e5216da44f612b20dfcd58a3336b48170225ee5de1eef0b77d9bcd0ccca
