---
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
erlang/otp_src_oss_20.3.8.1.tgz:
  size: 54645527
  object_id: 1d2a9c38-89b5-4cdf-6514-7cc94d5122ff
  sha: sha256:43e53cad8d8e9dcc905a6f2baedf315575f104426a32717f8416e5e5afb5ba0c
golang/go1.10.2.linux-amd64.tar.gz:
  size: 132481801
  object_id: ed7dc9dc-8d6c-4562-7f25-630ff5a2eacc
  sha: sha256:4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
haproxy/haproxy-1.6.13.tar.gz:
  size: 1580214
  object_id: 84b3dd36-e9f7-4917-aa31-67798f94975a
  sha: ae0cabea33c718b08d463016248facd31a3618b8
rabbitmq-server-3.6/rabbitmq-server-generic-unix-3.6.16.tar.xz:
  size: 4808464
  object_id: b9575b38-5483-44bb-4c4a-58de00155fb5
  sha: sha256:d7b0a5dbe670a79da7895b0dea6ccc74e778c3d309b6f7116e8ee4e2bd796b20
rabbitmq-server-3.7/rabbitmq-server-generic-unix-3.7.6.tar.xz:
  size: 9075236
  object_id: b23baa4a-a9ea-475b-51ab-ff50e2f540a2
  sha: sha256:23e61ec405fea9903c2de9532013feb124a5bc667a43a010c949276eda17e1d4
