---
# this comment prevents git conflicts
basht/basht_0.1.0_Linux_x86_64.tgz:
  size: 757703
  object_id: bbc2200b-670b-4562-72db-27ce98bc3161
  sha: 5dee8d242fc333672e14d9e1d70162b77eab5924
# this comment prevents git conflicts
erlang-24/otp_src_oss_24.3.4.4.tgz:
  size: 59993078
  object_id: 6f81013c-c468-4e44-689a-56f73b02e2fa
  sha: sha256:925c2aa816ea81947cfeca8772cde60b019461b6311190ae046d1c6a9b3c585f
# this comment prevents git conflicts
golang/go1.19.linux-amd64.tar.gz:
  size: 148796421
  object_id: 803a7168-5d6c-46cb-67e4-b80a2d3a38f4
  sha: sha256:464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6
# this comment prevents git conflicts
haproxy/haproxy-2.6.2.tar.gz:
  size: 3978933
  object_id: d41296cc-29d6-4bf9-79b8-0c58b50dbc6e
  sha: sha256:f9b7dc06e02eb13b5d94dc66e0864a714aee2af9dfab10fa353ff9f1f52c8202
# this comment prevents git conflicts
openssl/openssl-1.1.1q.tar.gz:
  size: 9864061
  object_id: f6b64f54-3a96-46e0-6488-4ffb05fbc50f
  sha: sha256:d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
# this comment prevents git conflicts
rabbitmq-server-3.8/rabbitmq-server-generic-unix-3.8.35.tar.xz:
  size: 15825620
  object_id: 7442d589-7af9-4353-5737-e396ad7551ed
  sha: sha256:09c970742b84209af5fe7e8f38ad8eaa9d074b798056bbe7dc83a7a32df3d9af
# this comment prevents git conflicts
rabbitmq-server-3.9/rabbitmq-server-generic-unix-3.9.22.tar.xz:
  size: 12761888
  object_id: 653d2b7d-0975-4eb6-762e-eeafaa3dc4d6
  sha: sha256:acf2fa033226ba389333562ec1684dfcc18a53bdf06162f29d3898c85b730be6
# this comment prevents git conflicts
rabbitmq-server-3.10/rabbitmq-server-generic-unix-3.10.7.tar.xz:
  size: 12818592
  object_id: 94246749-4b1b-49fd-48f4-4d36ee46121c
  sha: sha256:fcb424deb300635086f3bf554063af654bb58f2aa4e84126f514acc00439f5c2
