meta:
  default:
    rabbitmq_server:
      properties: {}
      templates: 
      - release: cf-rabbitmq
        name: rabbitmq-server

director_uuid: uuid
name: cf-rabbitmq

releases: 
  - <<: (( merge ))
  - name: cf-rabbitmq
    version: latest

jobs:
- name: rmq_z1
  templates: (( merge || meta.default.rabbitmq_server.templates ))
  instances: 1
  resource_pool: services-small-z1
  persistent_disk: 2048
  networks:
  - name: rabbitmq_z1
    static_ips: (( merge ))
  properties: (( merge || meta.default.rabbitmq_server.properties ))

- name: rmq_z2
  templates: (( merge || meta.default.rabbitmq_server.templates ))
  instances: 1
  resource_pool: services-small-z2
  persistent_disk: 2048
  networks:
  - name: rabbitmq_z2
    static_ips: (( merge ))
  properties: (( merge || meta.default.rabbitmq_server.properties ))

- name: rmq-broker
  release: cf-rabbitmq
  template: rabbitmq-broker
  instances: 1
  resource_pool: services-small-z1
  networks:
  - name: rabbitmq_z1
    static_ips: (( merge ))

- name: haproxy_z1
  release: cf-rabbitmq
  template: rabbitmq-haproxy
  instances: 1
  resource_pool: services-small-z1
  networks:
  - name: rabbitmq_z1
    static_ips: ((merge))

- name: haproxy_z2
  release: cf-rabbitmq
  template: rabbitmq-haproxy
  instances: 1
  resource_pool: services-small-z2
  networks:
  - name: rabbitmq_z2
    static_ips: ((merge))

- name: broker-registrar
  release: cf-rabbitmq
  template: broker-registrar
  instances: 1
  lifecycle: errand
  networks:
  - name: rabbitmq_z1
  properties:
    broker:
      host: (( "pivotal-rabbitmq-broker." .properties.cf.domain ))
      name: p-rabbitmq
      username: (( .properties.rabbitmq-broker.service.username ))
      password: (( .properties.rabbitmq-broker.service.password ))
  resource_pool: services-small-z1

- name: broker-deregistrar
  release: cf-rabbitmq
  template: broker-deregistrar
  instances: 1
  lifecycle: errand
  networks:
  - name: rabbitmq_z1
  properties:
    broker:
      host: (( "pivotal-rabbitmq-broker." .properties.cf.domain ))
      name: (( jobs.[5].properties.broker.name ))
      username: (( .properties.rabbitmq-broker.service.username ))
      password: (( .properties.rabbitmq-broker.service.password ))
  resource_pool: services-small-z1

- name: smoke-tests
  release: cf-rabbitmq
  template: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: rabbitmq_z1
  properties:
    broker:
      name: (( jobs.[5].properties.broker.name ))
  resource_pool: services-small-z1

properties:
  <<: (( merge ))
  cf:
    domain: cf_domain
    admin_password: cf_password
    admin_username: cf_username
    api_url: cf_api_url
    nats: 
      host: "" 
      port: "4222"
      password: nats_password 
      username: nats_username
  rabbitmq-server:
    plugins:
    - rabbitmq_management
    - rabbitmq_mqtt
    - rabbitmq_stomp
    administrators:
      broker:
        username: username
        password: password
    static_ips: (( merge )) 
    ssl:
      security_options:
      cert: 
      key: 
      cacert: 
  rabbitmq-haproxy:
    ports:
    - 5672
    - 5671
    - 1883
    - 8883
    - 61613
    - 61614
    - 15672
    - 15674
    server_ips: (( .properties.rabbitmq-server.static_ips ))
    stats:
      username: username
      password: password
  rabbitmq-broker:
    route: pivotal-rabbitmq-broker
    ip: (( jobs.[2].networks.[0].static_ips.[0] ))
    cc_endpoint: http://api.domain
    service:
      username: "p1-rabbit"
      password: "p1-rabbit-default-password"
      url: (( "http://" jobs.[2].networks.[0].static_ips.[0] ":4567" ))
    logging:
      level: debug
      print_stack_traces: false
    rabbitmq:
      operator_set_policy:
        enabled: true
        policy_name: "operator_set_policy"
        policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
        policy_priority: 50
      management_domain: pivotal-rabbitmq.(( .properties.cf.domain ))
      management_ip: (( jobs.[3].networks.[0].static_ips.[0] ))
      ssl: true
      hosts: (( merge ))
      administrator:
        username: (( .properties.rabbitmq-server.administrators.broker.username ))
        password: (( .properties.rabbitmq-server.administrators.broker.password ))
    uaa_client:
      <<: (( merge ))
networks: (( merge ))

resource_pools: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

compilation: (( merge ))
